version: "3.9"

services:
  db:
    image: mongo:6
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: 12345678
    volumes:
      - mongo_data:/data/db

  referral-system-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: referral-system-api:latest
    container_name: referral-system-api
    restart: always
    env_file: .env
    ports:
      - "4001:4001"

volumes:
  mongo_data:
