services:
  db:
    image: mongo:latest
    ports:
      - "27017:27017" 
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=12345678
    volumes:
      - mongo_data:/data/db
  
  
  referral-system-api:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PORT=4001
    image: referral-system-api:latest
    restart: always
    ports:
      - "4001:4001"

volumes:
  mongo_data: