FROM node:22-alpine

# Set environment variables
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"

# Enable corepack and install pnpm
RUN corepack enable

# Set the working directory
WORKDIR /app

# Copy package.json and pnpm-lock.yaml first to leverage Docker cache
COPY package*.json ./
COPY pnpm-lock.yaml ./

# Install dependencies
RUN pnpm install

# Copy the rest of the project files
COPY . .

# Expose the application port
EXPOSE 4001

# Command to start the development server with hot reloading
CMD ["pnpm", "run", "dev"]