# name: Referral System API

# on:
#   push:
#     branches: [ "main" ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v3

#     - name: Generate .env
#       run: |
#         cat > .env << 'EOF'
#         MODE=production
#         PORT=4001
#         MONGO_URI=${{ secrets.MONGO_URI }}
#         JWT_SECRET=${{ secrets.JWT_SECRET }}
#         EOF

#     - name: Login Dockerhub
#       env:
#         DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
#         DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
#       run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
#     - name: Build the Docker image
#       run: docker build -t sohan44512/referral-system .
#     - name: Push to Dockerhub
#       run: docker push sohan44512/referral-system:latest

#   deploy:
#     runs-on: self-hosted
#     needs: build
    
#     steps:
#     - name: Pull Docker image
#       run: sudo docker pull sohan44512/referral-system:latest
#     - name: Delete Old docker container
#       run: sudo docker rm -f referral-system-container || true
#     - name: Run Docker Container
#       run: |
#         sudo docker run -d \
#           --name referral-system-container \
#           -p 4001:4001 \
#           -e MODE=production \
#           -e PORT=4001 \
#           -e MONGO_URI=${{secrets.MONGO_URI}} \
#           -e JWT_SECRET=${{secrets.JWT_SECRET}} \
#           --restart unless-stopped \
#           sohan44512/referral-system:latest


name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

env:
  AWS_REGION: eu-north-1             
  ECR_REPOSITORY: referral-system-repo
  IMAGE_TAG: latest
  CONTAINER_NAME: referral-system-api

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and pnpm
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push Docker image
        run: |
          docker build -t $ECR_REPOSITORY:$IMAGE_TAG .
          docker tag $ECR_REPOSITORY:$IMAGE_TAG ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG
          docker push ${{ steps.login-ecr.outputs.registry }}/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            ECR_REPOSITORY="${{ env.ECR_REPOSITORY }}"
            IMAGE_TAG="${{ env.IMAGE_TAG }}"
            CONTAINER_NAME="${{ env.CONTAINER_NAME }}"
            AWS_ACCOUNT_ID=215771971945
            AWS_REGION="eu-north-1"

            echo "Pulling latest image from ECR..."
            sudo docker pull $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

            echo "Stopping old container (if running)..."
            sudo docker stop $CONTAINER_NAME || true
            sudo docker rm $CONTAINER_NAME || true

            echo "Running new container..."
            sudo docker run -d --name $CONTAINER_NAME \
              -e NODE_ENV=production \
              -e PORT=4001 \
              -e MONGO_URI='${{ secrets.MONGO_URI }}' \
              -e JWT_SECRET='${{ secrets.JWT_SECRET }}' \
              -p 4001:4001 \
              $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPOSITORY:$IMAGE_TAG

