name: Referral System API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t sohan44512/referral-system .
    - name: Push to Dockerhub
      run: docker push sohan44512/referral-system:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Pull Docker image
      run: sudo docker pull sohan44512/referral-system:latest
    - name: Delete Old docker container
      run: sudo docker rm -f referral-system-container || true
    - name: Run Docker Container
      run: sudo docker run -d -p 4001:4001 --name referral-system-container sohan44512/referral-system:latest