name: Referral System API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Generate .env
      run: |
        cat > .env << 'EOF'
        MODE=production
        PORT=4001
        MONGO_URI=${{ secrets.MONGO_URI }}
        JWT_SECRET=${{ secrets.JWT_SECRET }}
        EOF

    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t sohan44512/referral-system .
    - name: Push to Dockerhub
      run: docker push sohan44512/referral-system:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Pull Docker image
      run: sudo docker pull sohan44512/referral-system:latest
    - name: Delete Old docker container
      run: sudo docker rm -f referral-system-container || true
    - name: Run Docker Container
      run: |
        sudo docker run -d \
          --name referral-system-container \
          -p 4001:4001 \
          -e MODE=production \
          -e PORT=4001 \
          -e MONGO_URI=${{secrets.MONGO_URI}} \
          -e JWT_SECRET=${{secrets.JWT_SECRET}} \
          --restart unless-stopped \
          sohan44512/referral-system:latest