name: Referral System API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t sohan44512/referral-system .
    - name: Push to Dockerhub
      run: docker push sohan44512/referral-system:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Deploy MongoDB and API
      run: |
        # Pull latest images
        sudo docker pull sohan44512/referral-system:latest
        sudo docker pull mongo:7
        
        # Stop and remove old containers
        sudo docker stop referral-system-container referral-mongo || true
        sudo docker rm referral-system-container referral-mongo || true
        
        # Create network
        sudo docker network create referral-network || true
        
        # Run MongoDB with health check
        sudo docker run -d \
          --name referral-mongo \
          --network referral-network \
          -p 27017:27017 \
          -e MONGO_INITDB_ROOT_USERNAME=admin \
          -e MONGO_INITDB_ROOT_PASSWORD=password123 \
          -e MONGO_INITDB_DATABASE=referral_system \
          --restart unless-stopped \
          --health-cmd="mongosh --eval 'db.runCommand({ ping: 1 })'" \
          --health-interval=30s \
          --health-timeout=10s \
          --health-retries=3 \
          mongo:7
        
        # Wait for MongoDB to be ready
        echo "Waiting for MongoDB to be ready..."
        timeout 60 bash -c 'until sudo docker exec referral-mongo mongosh --eval "db.runCommand({ ping: 1 })" > /dev/null 2>&1; do sleep 2; done'
        
        # Run API container
        sudo docker run -d \
          --name referral-system-container \
          --network referral-network \
          -p 4001:4001 \
          -e NODE_ENV=production \
          -e PORT=4001 \
          -e MONGO_URI="mongodb://admin:password123@referral-mongo:27017/referral_system?authSource=admin" \
          --restart unless-stopped \
          --health-cmd="curl -f http://localhost:4001/health || exit 1" \
          --health-interval=30s \
          --health-timeout=10s \
          --health-retries=3 \
          sohan44512/referral-system:latest
        
        # Wait for API to be ready
        echo "Waiting for API to be ready..."
        timeout 60 bash -c 'until curl -f http://localhost:4001/health > /dev/null 2>&1; do sleep 2; done'
        
        # Show running containers
        sudo docker ps