name: Referral System API

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Login Dockerhub
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      
    - name: Build the Docker image
      run: docker build -t sohan44512/referral-system .
    - name: Push to Dockerhub
      run: docker push sohan44512/referral-system:latest

  deploy:
    runs-on: self-hosted
    needs: build
    
    steps:
    - name: Deploy with Docker Compose
      run: |
        # Pull latest API image
        sudo docker pull sohan44512/referral-system:latest
        
        # Stop existing services
        sudo docker-compose -f docker-compose.prod.yml down || true
        
        # Start services
        sudo docker-compose -f docker-compose.prod.yml up -d
        
        # Wait for services to be ready
        sleep 15
        
        # Check if services are running
        sudo docker ps
        
        # Test API health
        curl -f http://localhost:4001/health || echo "API health check failed"